# Keyboard
KEYBOARD_ROOT=36 #C2
KEYBOARD_MODE=0

# Arpeggiator
ARPEGGIATOR_MODE=0

# Midi
MIDI_CHANNEL=0 #0-15
MIDI_UART=1 #bool
MIDI_USB=1 #bool

# Audio
AUDIO_RATE=22050
AUDIO_BUFFER=2048

# Waveforms
WAVE_SAMPLES=256
WAVE_AMPLITUDE=12000
