version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  job:
    pre_build:
      - make -C circuitpython compile

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
