# Keyboard
KEYBOARD_ROOT=48 #C3
KEYBOARD_MODE=0

# Arpeggiator
ARPEGGIATOR_MODE=0

# Midi
MIDI_UART=1 #bool
MIDI_USB=1 #bool

# Audio
AUDIO_DRIVER="I2S"
AUDIO_RATE=22050
AUDIO_BUFFER=2048

# Waveforms
WAVE_SAMPLES=256
WAVE_AMPLITUDE=12000

# Microphone
MIC_RATE=8000
